### PR TITLE
Filtering and sorting features

### PR DESCRIPTION
**Pull request by claudenirmf**
This PR introduces the following features to the project:

- Sorting events based on startDate (ascending or descending) order

```
/event?sort=startDate
/event?sort=-startDate
```

- Filtering events based on `lastUpdate` date, date interval of ongoing events, interest events categories, proximity to a GPS location (longitude, latitude, and radius in meters), and available languages
- Filtering lifts based on `lastUpdate` date, interest lift categories, proximity to a GPS location, and available languages
- Filtering snowparks based on `lastUpdate` date, proximity to a GPS location, and available languages
- Filtering trails based on `lastUpdate` date, proximity to a GPS location, and available languages

```
/events?filter[lang]=eng,fra
/events?filter[categories]=schema/SportsEvent
/events?filter[updatedAfter]=2020-10-13
/events?filter[happeningAfter]=2020-10-13
/events?filter[happeningBefore]=2020-11-13
/events?filter[happeningBetween]=2020-10-13,2020-11-13
/events?filter[nearTo]=11.309245,46.862025,1000

/lifts?filter[lang]=eng
/lifts?filter[categories]=alpinebits/skilift,odh/sessellift
/lifts?filter[updatedAfter]=2020-10-01
/lifts?filter[nearTo]=11.309245,46.862025,10000

/snowparks?filter[lang]=ita
/snowparks?filter[updatedAfter]=2020-10-01
/snowparks?filter[nearTo]=11.891472,46.92275,10000

/trails?filter[lang]=ita
/trails?filter[updatedAfter]=2020-10-01
/trails?filter[nearTo]=11.309245,46.862025,10000
```

- Searching events that contain given a substring in their names (regardless of language)
- Searching lifts that contain given a substring in their names (regardless of language)
- Searching snowparks that contain given a substring in their names (regardless of language)
- Searching trails that contain given a substring in their names (regardless of language)

```
/event?_search[name]=bolzano

/lifts?_search[name]=renon

/snowparks?_search[name]=gardena

/trails?_search[name]=cross
```

Additional filtering, sorting, and searching options are possible but require new features on ODH's API to enable them.

Other updates in this PR include exporting multilingual fields in any available language and exporting event organizer IDs.

### CODE REVIEW

**Comment by RudiThoeni** [comment]
Hi @claudenirmf 

On the last meeting we said that you include the latest changes on this PR. 
when done can you write me a comment here or email so i will merge the PR and deploy, in the meantime i let this PR open

greetings
Rudi

**Comment by claudenirmf** [comment]
Hello @RudiThoeni,

I need to confirm some options we have for the syntax of the filters before we can merge this PR, but I'll let you know as soon as everything is sorted out.

If you prefer, you can lock the PR for review until I push new commits.

**Comment by RudiThoeni** [comment]
Hello @claudenirmf 
When the PR is ready just write down here and i will accept it ;)

**Comment by claudenirmf** [comment]
Hi @RudiThoeni! I've updated the filters, the search, and the random sorts queries. I have also added the handling of bad requests. Follows the updated list of queries.

- Random queries (accepts a number from 1 to 50 as valid seed)

```
/event?random=12
```

- Sorting queries (invalid when using random)

```
/event?sort=startDate
/event?sort=-startDate
```

- Filter queries (adds organizer filter by ID, only one organizer per request)

```
/events?filter[lang]=eng,fra
/events?filter[categories][any]=schema/SportsEvent
/events?filter[lastUpdate][gt]=2020-10-13
/events?filter[startDate][lte]=2020-10-13
/events?filter[endDate][gte]=2020-11-13
/events?filter[venues][near]=11.309245,46.862025,1000
/events?filter[organizers][eq]=22C0A7135D3341A481BECEC0DCDB373F

/lifts?filter[lang]=eng
/lifts?filter[categories][any]=alpinebits/skilift,odh/sessellift
/lifts?filter[lastUpdate][gt]=2020-10-01
/lifts?filter[geometries][near]=11.309245,46.862025,10000

/snowparks?filter[lang]=ita
/snowparks?filter[lastUpdate][gt]=2020-10-01
/snowparks?filter[geometries][near]=11.891472,46.92275,10000

/trails?filter[lang]=ita
/trails?filter[lastUpdate][gt]=2020-10-01
/trails?filter[geometries][near]=11.309245,46.862025,10000
```

- Search queries:

```
/event?search[name]=bolzano
/lifts?search[name]=renon
/snowparks?search[name]=gardena
/trails?search[name]=cross
```

This will be documented in OpenAPI in the next days and error responses will provide a link of the documentation to the client.

If you have any questions, let me know. As soon as you are ok with the PR, you can merge.

**Pull request merged**
